apiVersion: v1
kind: Service
metadata:
  name: {{ include "service-api.fullname" . }}
  labels:
    app: {{ include "service-api.name" . }}
    {{- include "service-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "service-api.selectorLabels" . | nindent 4 }}
